backend:
  name: github
  repo: ShinKano/Gatsby-Blog

media_folder: static/img
public_folder: /img

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog-posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: author, label: Author }
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - { name: body, label: Body, widget: markdown }